### ISSUE TITLE
object has no attribute 'degree'

### ISSUE THREAD

**Issue by LUOyk1999** [tufts-ml/graph-generation-EDGE#5]
Thank you for your outstanding work!
However, when I am running the "2. training template for large network datasets" for training, there is an error indicating that 'degree' does not exist in 'pyg_data' ("layers/layers.py", line 331). Traceback (most recent call last):
  File "train.py", line 88, in <module>
    exp.run()
  File "/mnt/data1/lyk/experiment/graph-generation-EDGE-main/diffusion/experiment.py", line 155, in run
    super(DiffusionExperiment, self).run(epochs=self.args.epochs)
  File "/mnt/data1/lyk/experiment/graph-generation-EDGE-main/diffusion/base.py", line 181, in run
    train_dict = self.train_fn(epoch)
  File "/mnt/data1/lyk/experiment/graph-generation-EDGE-main/experiment.py", line 32, in train_fn
    loss = elbo_bpd(self.model, pyg_data)
  File "/mnt/data1/lyk/experiment/graph-generation-EDGE-main/diffusion/loss.py", line 29, in elbo_bpd
    return loglik_bpd(model, x)
  File "/mnt/data1/lyk/experiment/graph-generation-EDGE-main/diffusion/loss.py", line 12, in loglik_bpd
    return -model.log_prob(x).sum() / (math.log(2) * x.num_entries)
  File "/mnt/data1/lyk/experiment/graph-generation-EDGE-main/diffusion/diffusion_base.py", line 185, in log_prob
    return self._train_loss(batched_graph)
  File "/mnt/data1/lyk/experiment/graph-generation-EDGE-main/diffusion/diffusion_binomial_active.py", line 248, in _train_loss
    kl = self._compute_MC_KL_joint(batched_graph, t, t_node, t_edge)
  File "/mnt/data1/lyk/experiment/graph-generation-EDGE-main/diffusion/diffusion_binomial_active.py", line 158, in _compute_MC_KL_joint
    log_model_prob_node, log_model_prob_edge = self._p_pred(batched_graph=batched_graph, t_node=t_node, t_edge=t_edge)
  File "/mnt/data1/lyk/experiment/graph-generation-EDGE-main/diffusion/diffusion_binomial_active.py", line 187, in _p_pred
    log_model_pred_node, log_model_pred_edge = self._predict_xtmin1_given_xt_st(batched_graph, t_node=t_node, t_edge=t_edge)
  File "/mnt/data1/lyk/experiment/graph-generation-EDGE-main/diffusion/diffusion_binomial_active.py", line 148, in _predict_xtmin1_given_xt_st
    out_node, out_edge = self._denoise_fn(batched_graph, t_node, t_edge)
  File "/home/lyk/miniconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data1/lyk/experiment/graph-generation-EDGE-main/layers/layers.py", line 331, in forward
    nodes_0 = pyg_data.degree[..., None] / self.max_degree
  File "/home/lyk/miniconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/data/data.py", line 428, in __getattr__
    return getattr(self._store, key)
  File "/home/lyk/miniconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/data/storage.py", line 65, in __getattr__
    f"'{self.__class__.__name__}' object has no attribute '{key}'")
AttributeError: 'GlobalStorage' object has no attribute 'degree'

**Comment by Xiaohui9607** [comment]
Can you check whether the "--degree" option is on?
